### PR TITLE
[#145] Image/icon abstraction

### LINKED ISSUE #145: [FEATURE] Image/icon abstraction
**Is your feature request related to a problem? Please describe.**
Currently there is no standard system in the client to manage icons and other image assets. This makes it challenging to keep image styling consistent throughout the app, update images, and add new images without repeating code.

**Describe the solution you'd like**
We should define a `UIImage` class which provides all of the necessary tools to load, style, and display images from various sources. 

From @mihail-varbanov:
> I like the concept of Image (UIIcon) abstraction nevertheless I have some remarks about the implementation. My suggestion is you to try adding a similar Image support to our Styles service:
> • The image definitions should come from styles.json.
> • The images that we will support will be the Flutter Image widget and FontAwesomeIcon widget (additional types, if any, are also welcome).
> • The Flutter’s Image widget could be loaded from asset, network, file or memory so that it can handle all the supported types.
> • Please look at the Flutter Image constructor parameters, see what is reasonable to be supported in our JSON definitions, and follow closely the model that they have.

### PR DESCRIPTION
**Pull request by roberlander2**
## Description
This PR adds the `UiImages` class to `Styles`, which is used to construct standard images defined in `styles.json`.

**Fixes #145**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [ ] Within a week
- [x] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Review by mihail-varbanov — CHANGES_REQUESTED** [review]
1. Please fix all build errors and warnings: [build_errors.json.txt](https://github.com/rokwire/app-flutter-plugin/files/9633839/build_errors.json.txt)

FYI, this is the current "official" flutter configuration for building rokwire project:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.5 21G72 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)

As far as I know today we should upgrade to a higher Flutter version. Please refer to project README for exact versions of Flutter, Android Studio, etc. Please make sure when you make the next PR to ensure the project build is working and there are no warnings.

2. Please provide some sample styles.json that contains various image definitions, including some images with all possible attributes defined.

3. Please define a factory constructor UiImages.fromJson and move there the JSON parsing logic from Styles.buildImagesData method.
Example: Roster.fromJson, InboxMessage.fromJson

3. Please make sure all reasonable Image attributes can be defined in "image" JSON section and overridden as parameters of UiImages.fromString. For example, I miss the "opacity" property.

4. Please fix the ModalImagePanel. Until we switch to Images abstraction it should support both methods: from imageUrl and from imageKey.

5. Please prefer the term "key" when you access image resources from style, not "src", "source", etc.
(example: UiColors.getColor).

Please find some more suitable name for UiImages.fromString, e.g. getImage, imageWithKey, or whatever else. We typically use fromString as a factory constructor name, e.g. UserRole.fromString or _StatusResponse.fromString.

I may come with more comments after I observe the image definition format that I requested in point 2.

**Comment by roberlander2** [comment]
Thanks @mihail-varbanov, I am working through your feedback now, and I will re-request your review once I finish. I want to get your thoughts on the following idea as well:

I think it could be worth adding a standard set of animations defined in `styles.json` to use in image JSON for the `opacity` field (similar to how `color` can reference the `color` map by key) and anywhere else they may be needed. The Illinois app looks like it uses a substantial number of animations, so do you think this would be worth implementing?

**Comment by mihail-varbanov** [comment]
Thanks for the info, @roberlander2.

Regarding the animations, I would put this aside for now. The reasons:

1. There are just 7 places we use animations (search for AnimationController);
2. It is not sure whether the animations will have to vary for different application brands;
3. Even if they have to, I would give this much lower priority than branding the main UI components like strings, text styles or images.
4. This is a separate task from the image abstraction that you currently work on so let's try to keep things simple.

**Comment by roberlander2** [comment]
Thanks @mihail-varbanov, I made the changes you requested and below is a sample `styles.json` with some sample colors and images.

    "color": {
        "fillColorPrimary"                      : "#00B5DE",
        "fillColorSecondary"                    : "#BF1993",
        "fillColorTertiary"                     : "#6CB50D",
    
        "fillColorPrimaryShade"                 : "#007F9B",
        "fillColorTertiaryShade"                : "#4E8209",
    
        "background"                            : "#F5F5F5",
        "surface"                               : "#FFFFFF",
        "surfaceAccent"                         : "#F8F8F8"
    },
    "font_family": {},
    "text_style": {},
    "image": {
        "image-all-params": {
            "type": "flutter.asset",
            "src": "images/example.png",
            "height": 24,
            "width": 24,
            "scale": 1.0,
            "alignment": "center",
            "fit": "cover",
            "color": "#ffffff",
            "color_blend_mode": "srcIn",
            "filter_quality": "none",
            "repeat": "noRepeat"
        },
        "logo-asset-large": {
            "type": "flutter.asset",
            "src": "images/logo.png",
            "height": 240,
            "fit": "fitWidth"
        },
        "logo-asset-medium": {
            "type": "flutter.asset",
            "src": "images/logo.png",
            "width": 140,
            "fit": "fitWidth"
        },
        "file-static": {
            "type": "flutter.file",
            "src": "path-to-file.png",
            "width": 120,
            "height": 120,
            "fit": "fitHeight"
        },
        "file-dynamic": {
            "type": "flutter.file",
            "width": 120,
            "height": 120,
            "fit": "fitHeight"
        },
        "memory-example": {
            "type": "flutter.memory",
            "width": 120,
            "height": 120,
            "fit": "fitWidth",
            "alignment": "centerLeft"
        },
        "network-static": {
            "type": "flutter.network",
            "src": "https://flutter.github.io/assets-for-api-docs/assets/widgets/falcon.jpg",
            "height": 140,
            "fit": "fitWidth"
        },
        "network-dynamic": {
            "type": "flutter.network",
            "height": 140,
            "fit": "fitWidth"
        },
        "circle-xmark-28-primary": {
            "type": "fa.regular",
            "src": "0xf057",
            "width": 28.0,
            "color": "fillColorPrimary",
            "text_direction": "ltr"
        },
        "circle-xmark-24-surface": {
            "type": "fa.regular",
            "src": "0xf057",
            "width": 24.0,
            "color": "surface",
            "text_direction": "ltr"
        }
    }

**Review by mihail-varbanov — APPROVED** [review]

**Comment by mihail-varbanov** [comment]
Hi @roberlander2,

Thanks, everything looks good. Approved and merged.

I have just 2 improvement comments:

1. I would use a single "fa-icon" value as "type" for Awesome font icon images, and would introduce a new field "weight", for example, with possible values of "regular", "solid" and "brands". Something like this:
```
{
  "type":"fa.icon",
  "weight":"regular",
  "src":"0xf057",
  …
}
```
I would not prebuild _faIconData in the UiImages constructor, I would build the IconData in _getFaIcon method like any other icon properties.
```
IconData ?faIconData;
switch (JsonUtils.stringValue(json['weight'])) {
  case 'solid': faIconData = IconDataSolid(code); break;
  case 'regular': faIconData = IconDataRegular(code); break;
  case 'brands': faIconData = IconDataBrands(code); break;
}
```
I will test for "flutter" and "fa" prefix in "type" to determine whether to build an FA icon or a Flutter Image widget.

What we have now works undoubtedly correctly but it just looks strange to me. Using the key persistence in _faIconData in order to determine the master image type (FA or Fluuter) works indeed but if we introduce another master type (e.g. owner draw path) we will have to make additional analysis.

2. I would consider what the following line of code actually does:

cbm ??= BlendMode.values.firstWhereOrNull((e) => e.toString() == 'BlendMode.${JsonUtils.stringValue(json['color_blend_mode']) ?? ''}');

I agree that it looks nice and clean. For me the problem is that you will execute JsonUtils.stringValue(json['color_blend_mode']) statement N times where N is the length of BlendMode.values list. This includes retrieval of a value from a hash map and some runtime type checks. This is not a big drama indeed but just not optimal for me.

**Comment by mihail-varbanov** [comment]
@roberlander2,

FYI, I implemented the above improvements. The FA icon definition format is changed like this:
```
"circle-xmark-28-primary":{
  "type":"fa.icon",
  "weight":"regular",
  "src":"0xf057",
  "size":28.0,
  "color":"fillColorPrimary",
  "text_direction":"ltr"
},
"circle-xmark-24-surface":{
  "type":"fa.icon",
  "weight":"regular",
  "src":"0xf057",
  "size":24.0,
  "color":"surface",
  "text_direction":"ltr"
}
```

**Comment by roberlander2** [comment]
Thanks @mihail-varbanov, I reviewed the changes you made to address your suggestions above, and I think they look good.

**Comment by mihail-varbanov** [comment]
Thanks @roberlander2. BTW, I do not know if you are aware about this but [this](https://github.com/rokwire/app-flutter-plugin/blob/develop/lib/service/styles.dart#L880-L882) usage of IconData requires `--no-tree-shake-icons` command line parameter when making release or profile builds.

**Comment by roberlander2** [comment]
> Thanks @roberlander2. BTW, I do not know if you are aware about this but [this](https://github.com/rokwire/app-flutter-plugin/blob/develop/lib/service/styles.dart#L880-L882) usage of IconData requires `--no-tree-shake-icons` command line parameter when making release or profile builds.

Thanks @mihail-varbanov, yes, I was aware that using this parameter when making builds would be necessary. If I understand correctly, this will just make the build sizes larger, but if this becomes an issue, we may be able to address it by excluding certain styles of `IconData` by customizing `font_awesome_flutter` as described here: https://pub.dev/packages/font_awesome_flutter#customizing-font-awesome-flutter

Using this, we could exclude styles that we do not use in the image JSON for a given app.

**Comment by mihail-varbanov** [comment]
Hi @roberlander2, to be honest I am not much into Font Awesome details. The release build just failed and I did not find other way to fix it. If you think that customizing font awesome plugin is a better solution that does not restrict the usage of FA icons please feel free to do it. BTW, the APK built with `--no-tree-shake-icons` got increased about 1 - 2 MB (from 73MB) so this does not seem a big deal in my opinion.

**Pull request merged**
