### PR TITLE
[#188] Survey rules remote notification action

### LINKED ISSUE #188: [FEATURE] Survey rules remote notification action
**Is your feature request related to a problem? Please describe.**
Currently we do not have a way to alert the relevant organization if concerning or otherwise notable survey responses are entered. 

**Describe the solution you'd like**
We should create a new rule action that makes use of the API introduced in https://github.com/rokwire/polls-building-block/issues/32 to send an alert with the relevant details to a pre-defined location.

**Describe alternatives you've considered**
Alerting could be handled entirely on the back-end, however we do not want to re-implement or partially implement the rules engine on the back end as well as the front end. These tasks would be computationally heavy for the back-end to be doing for every user, so it is better to keep this on the front-end.

### PR DESCRIPTION
**Pull request by roberlander2**
## Description
This PR implements the `notify` action used by the rules system. This action sends a request to the Polls BB to send alerts to specified contacts.
Depends on https://github.com/rokwire/polls-building-block/pull/37

**Fixes #188**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [ ] Within a week
- [x] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Comment by roberlander2** [comment]
@mihail-varbanov, this PR depends on https://github.com/rokwire/polls-building-block/pull/37, so a review here can wait until that is done. Thanks!

**Comment by mihail-varbanov** [comment]
@roberlander2, let me know please when the time for review of this PR comes.

**Review by shurwit — COMMENTED** [review]
Thanks @roberlander2, this is looking good and seems to functionaing as expected. The only issue I see is that we also want to be able to populate the alert body with information about the user. Specifically, the alerts should currently contain the following:

**Subject:** Automatic submission from Illinois app
**Body:** Student name, UIN, screener name, "Flagged for intervention"

**Comment by shurwit** [comment]
Hi @mihail-varbanov, we are ready for this PR to be merged. Thanks!

**Review by mihail-varbanov — CHANGES_REQUESTED** [review]
1. Auth2 model & service and Service abstract class are more basic than Surveys. They should not include and depend on the Survey model. Particularly, you should resolve locally in Survey the following methods currently places in Auth2 and Survey:

Auth2UserPrefs.getProperty
Auth2UserProfile.getProperty
Service.getProperty
Auth2.getProperty

2. I believe that this line should be removed:
https://github.com/rokwire/app-flutter-plugin/blob/188-survey-rules-remote-notification-action/lib/model/auth2.dart#L1051

**Comment by shurwit** [comment]
> 1. Auth2 model & service and Service abstract class are more basic than Surveys. They should not include and depend on the Survey model. Particularly, you should resolve locally in Survey the following methods currently places in Auth2 and Survey:
> 
> Auth2UserPrefs.getProperty Auth2UserProfile.getProperty Service.getProperty Auth2.getProperty
> 
> 2. I believe that this line should be removed:
>    https://github.com/rokwire/app-flutter-plugin/blob/188-survey-rules-remote-notification-action/lib/model/auth2.dart#L1051

Thanks for the feedback @mihail-varbanov, I believe I have addressed your concerns. Please take another look when you get a chance. Thanks again!

**Review by mihail-varbanov — APPROVED** [review]
Thanks @shurwit, everything looks good to me now.

**Pull request merged**
