### PR TITLE
[#408] Improve services init on app startup

### LINKED ISSUE #408: [FEATURE] Improve services init on app startup
**Is your feature request related to a problem? Please describe.**
The current version of `Services().init()` is functional, but it does not initialize all services as quickly as possible. Services are initialized synchronously, so some services which have no dependencies or have dependencies which are already initialized will need to wait on unrelated services before beginning initilization.

**Describe the solution you'd like**
`Services().init()` should be updated to initialize services asynchronously. All services with no dependencies (e.g., Storage) should begin initialization immediately, and when any service completes initialization, any service that depends on it should start initialization as long as all of its other dependencies have been initialized.

**Describe alternatives you've considered**
This change is not necessary for apps to function correctly, but it will likely improve startup times for apps that use many services.

### PR DESCRIPTION
**Pull request by roberlander2**
## Description
This PR improves the efficiency of `Services().init()`, so app startup times should improve. The new implementation uses `serviceDependsOn` to identify service dependencies and begin service initialization as soon as all dependencies are initialized.

**Fixes #408**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [x] Within a week
- [ ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Comment by roberlander2** [comment]
Hi @mihail-varbanov, please take a look at these changes when you have time. I tested this on the Vogue app and it appears to be working as expected, but let me know if you see any issues with it or have any questions. Thanks!

**Review by mihail-varbanov — COMMENTED** [review]
Hi @roberlander2,

1. I find your algorithm for services initialization too complex and confusing. In general, my understanding is that it should not be recursive. Instead, my belief is that we should use the Breadth First Search (BFS) algorithm to traverse and initialize all services in their correct order.

2. In addition, the BFS algorithm gives a more sophisticated way to detect loops in a graph, way better than the current handling which results in "All services have dependencies. No services may be initialized safely.".

3. I think that you should obey the fatal service initialization errors. They indicate a state when the further initialization should be suspended (i.e. the other services that depend on this service should not be attempted to be initialized). A good example of fatal service initialization error is to fail to load the app config on the first launch when there is no cached version of its data yet.

4. Currently if a given service fails initServiceFallback is applied to all services while it should be applied only to the services that depend on that service. Then, all these service (that has initServiceFallback applied) are initialized in the normal way, i.e. I do not see the point of initServiceFallback invocation.

5. Service.serviceDependsOn API describes dependency only during initService session. Since AppDateTime.initService does not make any calls to any other service, the dependency that you added to AppDateTime is wrong.

6. Finally,  a minor technical note: Every time you call Service.serviceDependsOn you generate a new array. It is worth it to create  this array once and keep it until it is no more needed.

CC @shurwit.

**Comment by roberlander2** [comment]
Thank you @mihail-varbanov for your response. I want to address some of your comments to clarify the algorithm a bit.

1. The reason why my algorithm is recursive is because it tries to start service initialization as soon as all the service's dependencies have been initialized. It starts by immediately calling `initService` on all of the services without dependencies, then as each of those services finishes initialization, it attempts to begin initialization for all services that depend on each of them, and so on until services that no other services depend on are initialized (the "base case"). The issue I see with the original implementation is that services are initialized one at a time, so some services may need to wait unnecessarily for some unrelated services to initialize first, which slows app startup.

2. You are right that my algorithm does not explicitly detect dependency loops, but it is able to handle them by not attempting initialization for any services in the loop or any dependencies of services in the loop and then reporting the uninitialized services to the developer with `verifyInitialization()`. It may be worth being more precise with reporting dependency loops to developers, but I don't think it is critical.

3-6. I agree with everything you said here and I believe I have addressed all of those issues. Please let me know if you still see an issue with any of these items.

Let me know if you have any other questions or concerns. Thanks!

**Comment by mihail-varbanov** [comment]
Hi @roberlander2,

I understand what your algorithm does and what issue it attempts to resolve, BTW, this was in my internal TODO list for UIUC app for long time.

However the recursive algorithm (depth-first graph traversal) is not the only one to traverse and initialize the set of linked services. What I wanted was to use Breadth First Search (BFS) algorithm for this because I find it more applicable in our case.

Anyway, I implemented it in a separate branch and created PR #411 to you. Please look at it and if you think that I have not broken anything working please approve and merge it. After that please feel free to merge your [original](https://github.com/rokwire/app-flutter-plugin/tree/408-services-init-on-app-startup) branch to [vogue](https://github.com/rokwire/app-flutter-plugin/tree/vogue) branch.

**Comment by roberlander2** [comment]
Hi @mihail-varbanov,

I took a look at your changes in #411, and I believe BFS would perform as well as the recursive algorithm for the Vogue app because of the init times of the individual services, but I don't think BFS is always optimal.

As an example, I did some testing with the Vogue app where I added `HttpProxy()` as a dependency of the `Styles()` service. In the BFS algorithm, this moves `Styles()` from the third to the fourth entry in `initList` [here](https://github.com/rokwire/app-flutter-plugin/blob/408-services-init-on-app-startup-BFS/lib/service/service.dart#L201). The `Auth()` service remains in the third entry, which means now `Styles()` must wait for `Auth()` to finish initializing before it may start even though it and none of its ancestors depend on `Auth()`.

We may run into situations similar to this example in other applications, and depending on the individual service startup times, the overall app startup time of BFS may not always match the recursive solution. Do you have a way to address this in the BFS algorithm?

**Comment by shurwit** [comment]
Hi @mihail-varbanov @roberlander2, thank you both for your work and discussion on this issue! I have been reading through both of your comments and have discussed this a bit with @roberlander2. @mihail-varbanov I do see the value in detecting cycles and being able to explicitly display them to the developers to facilitate debugging, however I do agree with @roberlander2's explanation about why his recursive algorithm will be theoretically optimal when compared to your BFS algorithm. 

I think the exact issue that is introduced by the BFS approach may not have been clear in @roberlander2's previous description so I did a quick drawing to compare the two on a simple case that illustrates the problem:



We can see here that by breaking the initialization process into stages we are reintroducing some of the serialization that we were hoping to avoid by implementing this change to begin with. As shown this means that if we have a few slow services in different stages of the BFS algorithm that don't depend on each other they will end up getting stuck waiting on each other to initialize even when this is not necessary. In contrast, the recursive algorithm avoids this issue and allows each service to begin initialization at the exact moment that all of it's precise dependencies have finished initializing. 

It is true that the recursive algorithm cannot explicitly detect cycles but this should never impact a production application, only the debugging process. My feeling is that we should not be sacrificing the optimality of the initialization times in production in favor of slightly improved debugging for developers. If you really do feel that it is critical to detect cycles, we could even run a cycle detection algorithm in the case where the recursive algorithm does happen to run into an error in order to identify the cycle and display more details to the developer.

While the algorithms may perform similarly on the Illinois app at the moment, this may not always be the case as we introduce more services or change existing ones, and certainly may not be true for other apps we use the plugin with. 

A couple of notes on a few other comments I have seen. 
1) I noticed that there are some experimental comparisons of timing results between these two algorithms. While I agree that this is worth taking a look at, I do not believe this will actually give us a complete picture of what is happening since the service initialization times can vary drastically between runs due to network delays. Rather, my feeling is that we should focus on the logic of the algorithms themselves and do a theoretical comparison based on equal timings as I demonstrated in the drawing above.
2) In my opinion we should set aside the question of readability and code style for this discussion since this is pretty subjective and it does not seem to me that one algorithm to be clearly more readable or maintainable than the other.

I agree that it may not be worth spending too much more time on this for marginal time saves on initialization, but I figure it is best to settle the conversation once and for all now rather than needing to revisit it in the future. Please let me know if either of you have any comments on the thoughts I shared here. 

Thanks again!

**Comment by mihail-varbanov** [comment]
Hi @shurwit,

I generally agree with your analysis.

I think that you underestimate the question for readability and clearness of the algorithm, because this is not a static final source code, it is live and must be maintained and developed by different people.

I 200% agree with you about "spending too much more time on this for marginal time saves on initialization". In addition, I would bring your attention to the fact that the application startup happens quite rarely, most of the cases the application is invoked it is just awakened from the background.

Thanks!

**Comment by mihail-varbanov** [comment]
Hi @shurwit,

I am afraid I did not express myself correctly before. The problem with this PR is not in the complexity of the algorithm that it uses. The problem is rather in its implementation. In my opinion it is not clear enough, it is more complex than necessary and a little confusing for me. Кeeping the source code simple, clear, and efficient is of great importance to me. I guess you would say again that this is subjective. I agree, but as far as I am the person who currently takes the decision whether a given source code is good and suitable for merging or not, I prefer to follow my own common sense.

In order to find "the best approach to take that we can all live with", I implemented the "recursive" algorithm from the [408-services-init-on-app-starup](https://github.com/rokwire/app-flutter-plugin/tree/408-services-init-on-app-startup) branch in a way that I find simple, clear, and efficient enough. It is located in the [408-services-init-on-app-starup-V2](https://github.com/rokwire/app-flutter-plugin/tree/408-services-init-on-app-starup-V2) branch. Please take a look at it and if it also meets your criteria I am going to merge it in the main plugin's branch. If you have any comments or concerns, please share them with me.

Thanks!

**Comment by mihail-varbanov** [comment]
Thank you, @shurwit! I have to admit that the last version of the service initialization process looks simpler, clearer and more effective to me than my previous BFS implementation. This is thanks to your persistence, @shurwit, so thank you for helping us reach a better solution.

**Comment by shurwit** [comment]
> Thank you, @shurwit! I have to admit that the last version of the service initialization process looks simpler, clearer and more effective to me than my previous BFS implementation. This is thanks to your persistence, @shurwit, so thank you for helping us reach a better solution.

Thanks @mihail-varbanov, for bearing with us and for doing the final implementation! I'm glad we were able to find a solution that we all feel good about. We appreciate all your input and help as always!

**Pull request closed without merging**
